export const content = {
  nav: { work: "Work", about: "About", skills: "Skills", experience: "Experience", study: "Study" },
  hero: {
    greeting: "Based in Ho Chi Minh City",
    name: "Kane",
    tagline: "I build with a backend-first mindset, keep the workflow keyboard-heavy, and like interfaces that stay clear under real use.",
    facts: ["Ho Chi Minh City"],
    ctaWork: "View work",
    ctaCv: "Download CV",
    console: {
      title: "boot kane",
      version: "v1.0",
      command: "./kane",
      rows: [
        { label: "alias", value: "Kane" },
        { label: "formal", value: "Le Duy Khang" },
        { label: "location", value: "Ho Chi Minh City" },
        { label: "current", value: "WALA-ICT" },
        { label: "editor", value: "Neovim + IdeaVim" },
        { label: "mode", value: "shipping with clean loops" },
      ],
    },
  },
  about: {
    title: "About",
    description: "A short intro to Kane, the work I ship, and how I like to build.",
    body: [
      "I'm Kane, a software engineer from Ho Chi Minh City.",
      "I enjoy building software that is actually useful, not just polished on the surface. My work tends to focus on practical systems, cleaner workflows, and tools that make everyday engineering faster and simpler.",
      "Most of my recent experience has been with Java and Spring, and lately I've been pushing further into Go while continuing to sharpen how I work.",
      "I value simplicity, speed, and steady improvement over unnecessary complexity.",
    ],
    facts: [
      { label: "Location", value: "Ho Chi Minh City" },
      { label: "Current", value: "WALA-ICT" },
      { label: "Focus", value: "Java, Spring Boot, Go, Python, React, TypeScript" },
      { label: "Experience", value: "1y+ real projects" },
    ],
  },
  config: {
    title: "Config",
    description: "The setup behind the work: a small look at the editor habits, keymaps, and defaults I keep close every day.",
    intro: "I treat config as working infrastructure, not decoration. The goal is faster navigation, less context switching, and muscle memory that survives across lightweight editors and full IDE sessions.",
    repoLinks: [
      { label: "Neovim config", href: "https://github.com/LDKhangg/nvim-config" },
      { label: "IdeaVim config", href: "https://github.com/LDKhangg/dotfiles-vim" },
    ],
    cards: [
      {
        title: "Neovim",
        kicker: "Daily driver",
        items: [
          "LSP, completion, and diagnostics tuned for getting feedback early instead of after a broken build.",
          "Terminal-first editing flow with quick project movement, grep-heavy navigation, and low-friction file switching.",
          "UI choices stay quiet on purpose: readable contrast, sensible motion, and just enough signal to avoid visual noise.",
        ],
      },
      {
        title: "IdeaVim",
        kicker: "Same muscle memory in the IDE",
        items: [
          "Core motions and leader habits stay close to Neovim so IntelliJ does not feel like a context reset.",
          "Used when deep Java work needs richer inspections, debugging, and refactors without losing keyboard flow.",
          "The point is consistency: the editor can change, but how I think and move through code should not.",
        ],
      },
    ],
    principlesLabel: "Principles",
    principles: [
      "Optimize for clarity before novelty.",
      "Keep muscle memory portable across tools.",
      "Use config to remove friction, not add ceremony.",
    ],
  },
  activity: {
    title: "Coding activity",
    description: "A quick view of LeetCode progress and the repos that moved most recently.",
    refreshed: "Refreshed from public GitHub data",
    loadingLabel: "Loading",
    progressLabel: "Progress",
    solvedLabel: "Solved",
    easyLabel: "Easy",
    mediumLabel: "Medium",
    hardLabel: "Hard",
    progressNote: "Computed from the real repository structure inside the leetcode repo.",
    contributionLabel: "Contributor board",
    contributionNote: "A last-year contribution view pulled from the public GitHub profile.",
    contributionAlt: "GitHub contribution chart for LDKhangg",
    contributionAction: "View on GitHub",
    latestLabel: "Latest update",
    latestNote: "The four repos that moved most recently, based on the newest public commits.",
    repositoryLabel: "Repository",
    updatedLabel: "Updated",
    unavailableLabel: "Unavailable",
    latestAction: "Open commit",
    latestListLabel: "Recent repos",
  },
  projects: {
    title: "Project folders",
    description: "Open a folder to inspect the product, what I owned, and the stack behind it.",
    openProject: "Open project",
    stackLabel: "Stack",
    items: [
      {
        name: "Locker R — Smart Locker IoT Platform",
        role: "Graduation project · Fullstack",
        description:
          "Distributed backend of 11 Spring Boot microservices behind Spring Cloud Gateway. RabbitMQ events, MQTT locker hardware, real-time tracking over WebSocket/STOMP, JWT RBAC, and CI/CD to DigitalOcean.",
        stack: ["Java 21", "Spring Cloud", "RabbitMQ", "MQTT", "PostgreSQL", "Docker"],
        link: "https://github.com/LDKhangg/Locker-EXE-Graduation",
      },
      {
        name: "B2B Construction E-Procurement",
        role: "WALA-ICT · Backend",
        description:
          "Multi-tenant procurement platform — quote requests, bidding, contracts, claims, invoicing. Hexagonal architecture, tenant-scoped RBAC, Redis-backed security layer with distributed rate limiting.",
        stack: ["Java 21", "Spring Boot", "MyBatis", "PostgreSQL", "Redis", "GitLab CI"],
        link: null,
      },
      {
        name: "Fitness Studio Franchise SaaS",
        role: "WALA-ICT · Fullstack",
        description:
          "Nationwide fitness-franchise SaaS — memberships, ticket commerce, coupon campaigns, revenue settlement. Spring Boot services by bounded context plus a React 19 admin.",
        stack: ["Spring Boot 3", "QueryDSL", "MySQL", "Redis", "React 19", "TypeScript"],
        link: null,
      },
    ],
  },
  skills: {
    title: "Skills and config",
    description: "The stack I use most, plus the editor and config habits that keep the day-to-day workflow fast.",
    groups: [
      { label: "Backend", items: "Java · Spring Boot · Go · Spring Security · JPA/Hibernate · MyBatis · QueryDSL · REST" },
      { label: "Frontend", items: "React · TypeScript · Zustand · TanStack Query · styled-components · Tailwind" },
      { label: "Data & Messaging", items: "PostgreSQL · MySQL · Redis · RabbitMQ · MQTT · WebSocket/STOMP" },
      { label: "DevOps & Cloud", items: "Docker · GitHub Actions · GitLab CI · AWS (EC2, S3, RDS, IAM)" },
    ],
  },
  experience: {
    title: "Experience",
    description: "A short timeline of paid work and cloud training.",
    items: [
      { org: "WALA-ICT", role: "Fullstack Software Developer", time: "Jun 2025 — Present", note: "Built ERP and multi-tenant business features with React and Java/Spring Boot, worked with BAs and developers in Scrum, integrated APIs, and supported testing and releases." },
      { org: "AWS First Cloud Journey", role: "Cloud Training Program", time: "Sep — Nov 2025", note: "Hands-on AWS labs covering EC2, S3, RDS, and IAM as part of the cloud training program." },
    ],
  },
  certs: {
    title: "Study and certifications",
    description: "Education and recent training that back up the work above.",
    items: [
      { name: "FPT University — Software Engineering", detail: "2022 — 2026" },
      { name: "AWS First Cloud Journey", detail: "Completed hands-on cloud program, 2025" },
      { name: "English — CEFR B2", detail: "EnglishScore, ≈785 TOEIC" },
    ],
  },
  contact: {
    title: "Contact",
    blurb: "If you want to talk backend, frontend, or product work, email me.",
    email: "contact.ldkhang@gmail.com",
    footer: "Built with React · Deployed on GitHub Pages",
    description: "The fastest way to reach me is email.",
    statsAlt: "GitHub stats",
    langsAlt: "Top languages",
  },
} as const;
